#!/usr/bin/env bash

## Set colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

## If .git directory does not exists exit
if [ ! -d ".git" ]; then
  printf "\n${RED}ERROR: Not a valid git repository \n";
  exit 1
fi

# Fetch all recent branches sorted by recency of commit
branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format='%(refname:short)')

# Convert branch string to array of branch names
arr=()
while read -r line; do
   arr+=("$line")
done <<< "$branches"

# Present the list to the user
counter=1
for i in "${arr[@]}"
do
        printf "   ${RED}$counter${NC}  $i\n"
        counter=$((counter+1))
done

# Take input from user
printf "\n${GREEN}Enter the branch number to be checked out: "
read userInput
userInput=$((userInput-1))

if [ $userInput -gt ${#arr[@]} ] || [ $userInput -eq ${#arr[@]} ] || [ $userInput -eq -1 ]; then
  printf "\n${RED}ERROR: No branch selected. abort. \n";
  exit 1
fi

# Check out the selected branch
git checkout ${arr[$userInput]}
